name: CI
on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0
      - name: install Graphviz
        run: sudo apt install graphviz
        shell: bash
      - name: poetry install
        run: poetry install
      - name: for debug1
        run: |
          echo $VIRTUAL_ENV
      #- name: for debug2
      #  run: |
      #    import sys
      #    import pprint
      #    pprint.pprint(sys.path)
      #  shell: python
      - name: draw diagram
        env:
          RUNNING_AT: workflow
        run: |
          python ./main_diagram.py
        shell: bash
      - name: configure git
        env:
          TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          UNAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --local user.name ${UNAME}
          git config --local user.email ${EMAIL}
          git remote set-url origin https://${UNAME}:${TOKEN}@github.com/${UNAME}/diagram_by_diagrams
      - name: git commit
        run: |
          git add -A
          if [ $(git diff --cached --numstat | wc -l) -eq 0 ]; then
            echo "no difference found"
            exit 0
          fi
          git commit -am 'Update diagram pushed by workflow'
        shell: bash
      - name: git push
        run: git push origin HEAD
        shell: bash
